services:
  app:
    build:
      context: .
    environment:
      GOMODCACHE: /go/src/app/.modcache
      GOCACHE: /go/src/app/.cache
    volumes:
      - "./app:/go/src/app"
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: appdb
    volumes:
      - "./.service-db:/var/lib/mysql"
    ports:
      - "3333:3306"
